fix(internal): run gofmt during supplemental codegen

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -12,5 +12,13 @@ if ! git diff --exit-code; then
     exit 1
 fi
 
+echo "==> Checking for misformatted code"
+scripts/format
+if ! git diff --exit-code; then
+    echo "error: code formatting is incorrect" >&2
+    echo " hint: run \`scripts/format\` to fix the formatting" >&2
+    exit 1
+fi
+
 echo "==> Running Go build"
 go build ./...
